version: '3.7'
services:
  mijn-website:
    container_name: mijn-website
    build: .
    ports:
      - '49160:8181'
  swag:
    cap_add:
      - NET_ADMIN
    container_name: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=davidduyff.nl
      - SUBDOMAINS=www,test
      - VALIDATION=http
    image: 'ghcr.io/linuxserver/swag'
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped
    volumes:
      - '${PWD}/config:/config'